// AUTO-GENERATED by build-rules.js — do not edit by hand.
// Rebuild: node build-rules.js
export const RULESETS = {
  "finance": {
    "name": "Finance · expense control",
    "desc": "Reimbursement limits (travel > 3000 blocked)",
    "ruleCount": 6,
    "transform": [
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_expense_limit_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.expense.type",
                  "value": "travel"
                },
                "on_true": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "not",
                        "inner": {
                          "type": "lt",
                          "path": "__exec__.payload.data.expense.amount",
                          "value": 3000
                        }
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "blocked"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.reason",
                            "operation": "set",
                            "value": "差旅报销超限额3000元"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "allowed"
                          }
                        }
                      ]
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "eq",
                        "path": "__exec__.payload.data.expense.type",
                        "value": "meal"
                      },
                      "on_true": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "not",
                              "inner": {
                                "type": "lt",
                                "path": "__exec__.payload.data.expense.amount",
                                "value": 1500
                              }
                            },
                            "on_true": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "blocked"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.reason",
                                  "operation": "set",
                                  "value": "餐饮报销超限额1500元"
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "allowed"
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "eq",
                              "path": "__exec__.payload.data.expense.type",
                              "value": "office"
                            },
                            "on_true": [
                              {
                                "type": "branch",
                                "params": {
                                  "domain": {
                                    "type": "not",
                                    "inner": {
                                      "type": "lt",
                                      "path": "__exec__.payload.data.expense.amount",
                                      "value": 800
                                    }
                                  },
                                  "on_true": [
                                    {
                                      "type": "set",
                                      "params": {
                                        "attr": "__exec__.payload.data.result.decision",
                                        "operation": "set",
                                        "value": "blocked"
                                      }
                                    },
                                    {
                                      "type": "set",
                                      "params": {
                                        "attr": "__exec__.payload.data.result.reason",
                                        "operation": "set",
                                        "value": "办公用品报销超限额800元"
                                      }
                                    }
                                  ],
                                  "on_false": [
                                    {
                                      "type": "set",
                                      "params": {
                                        "attr": "__exec__.payload.data.result.decision",
                                        "operation": "set",
                                        "value": "allowed"
                                      }
                                    }
                                  ]
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "allowed"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_approval_routing_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "lt",
                  "path": "__exec__.payload.data.expense.amount",
                  "value": 500
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "auto_approved"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "lt",
                        "path": "__exec__.payload.data.expense.amount",
                        "value": 5000
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "manager_approval"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.escalate_to",
                            "operation": "set",
                            "value": "部门经理"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "lt",
                              "path": "__exec__.payload.data.expense.amount",
                              "value": 30000
                            },
                            "on_true": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "director_approval"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.escalate_to",
                                  "operation": "set",
                                  "value": "分管副总"
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "collective_approval"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.escalate_to",
                                  "operation": "set",
                                  "value": "总经理办公会集体审批"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_invoice_compliance_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "not",
                  "inner": {
                    "type": "has_fields",
                    "path": "__exec__.payload.data.invoice",
                    "fields": [
                      "invoice_no",
                      "buyer_name",
                      "buyer_tax_id",
                      "amount",
                      "date"
                    ]
                  }
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "rejected"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "发票缺少必填字段（发票号码/购买方名称/纳税人识别号/金额/开票日期至少一项缺失）"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "eq",
                        "path": "__exec__.payload.data.invoice.buyer_tax_id",
                        "value": ""
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "rejected"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.reason",
                            "operation": "set",
                            "value": "纳税人识别号格式不符（应为15/17/18/20位字母数字，此处为空）"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "compliant"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_expense_split_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.split_suspected",
                  "value": true
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "split_detected"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "疑似拆单：同供应商同日多笔合计超5000元（分组聚合由上游预算/报销服务完成，本规则编码处置策略）"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "no_split"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_budget_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.budget.within_budget",
                  "value": true
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.remaining",
                      "operation": "set",
                      "value": "__exec__.payload.data.budget.remaining"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "超预算：科目余额不足"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "finance_storage_encryption_gate"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "exists",
                      "path": "__exec__.payload.data.operation.fields.id_card"
                    },
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.encryption",
                      "value": "none"
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.8.b：敏感数据未加密存储，已阻断并留痕"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      }
    ]
  },
  "medical": {
    "name": "Medical · antibiotic tiers",
    "desc": "Special-tier antibiotics are outpatient-blocked (ML Decree No.84)",
    "ruleCount": 6,
    "transform": [
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_antibiotic_tier_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.prescription.antibiotic_tier",
                      "value": "special"
                    },
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.visit.type",
                      "value": "outpatient"
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "特殊使用级抗菌药物不得在门诊使用（卫生部令84号第二十七条）"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "all",
                        "inner": [
                          {
                            "type": "eq",
                            "path": "__exec__.payload.data.prescription.antibiotic_tier",
                            "value": "restricted"
                          },
                          {
                            "type": "not",
                            "inner": {
                              "type": "eq",
                              "path": "__exec__.payload.data.prescriber.title",
                              "value": "attending"
                            }
                          },
                          {
                            "type": "not",
                            "inner": {
                              "type": "eq",
                              "path": "__exec__.payload.data.prescriber.title",
                              "value": "chief"
                            }
                          }
                        ]
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "blocked"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.reason",
                            "operation": "set",
                            "value": "限制使用级需主治医师及以上处方权（卫生部令84号第二十四条）"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "allowed"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_drug_indication_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.diagnosis.type",
                  "value": "viral"
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "病毒性感染无抗菌药物使用指征（2015指导原则：病毒性感染者均无应用抗菌药物指征）"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "eq",
                        "path": "__exec__.payload.data.diagnosis.type",
                        "value": "bacterial"
                      },
                      "on_true": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "eq",
                              "path": "__exec__.payload.data.lab.has_drug_sensitivity",
                              "value": true
                            },
                            "on_true": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "allowed"
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "warning"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.reason",
                                  "operation": "set",
                                  "value": "建议完善药敏试验（卫生部令84号第三十一条）"
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "need_more_info"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_drug_allergy_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.patient.has_penicillin_allergy",
                      "value": true
                    },
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.prescription.drug_class",
                      "value": "penicillin"
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "青霉素过敏者禁用青霉素类药物（药品说明书禁忌）"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_antibiotic_override_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.prescription.is_emergency_override",
                  "value": true
                },
                "on_true": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "eq",
                        "path": "__exec__.payload.data.prescription.paperwork_filed",
                        "value": true
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "allowed"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "not",
                              "inner": {
                                "type": "lt",
                                "path": "__exec__.payload.data.prescription.hours_since_prescription",
                                "value": 25
                              }
                            },
                            "on_true": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "blocked"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.reason",
                                  "operation": "set",
                                  "value": "越级使用超24小时未补办手续（卫生部令84号第二十八条）"
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "allowed"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.reason",
                                  "operation": "set",
                                  "value": "急诊越级使用，须于24小时内补办手续（卫生部令84号第二十八条）"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_triage_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "not",
                      "inner": {
                        "type": "lt",
                        "path": "__exec__.payload.data.patient.age",
                        "value": 65
                      }
                    },
                    {
                      "type": "not",
                      "inner": {
                        "type": "lt",
                        "path": "__exec__.payload.data.patient.temperature_tenths",
                        "value": 385
                      }
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "urgent"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "高龄高热（≥65岁且≥38.5℃），优先分诊"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "not",
                        "inner": {
                          "type": "lt",
                          "path": "__exec__.payload.data.patient.temperature_tenths",
                          "value": 395
                        }
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "urgent"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.reason",
                            "operation": "set",
                            "value": "高热≥39.5℃，优先分诊"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "branch",
                          "params": {
                            "domain": {
                              "type": "all",
                              "inner": [
                                {
                                  "type": "not",
                                  "inner": {
                                    "type": "lt",
                                    "path": "__exec__.payload.data.lab.wbc",
                                    "value": 15000
                                  }
                                },
                                {
                                  "type": "not",
                                  "inner": {
                                    "type": "lt",
                                    "path": "__exec__.payload.data.lab.crp",
                                    "value": 50
                                  }
                                }
                              ]
                            },
                            "on_true": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "urgent"
                                }
                              },
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.reason",
                                  "operation": "set",
                                  "value": "感染指标显著升高（WBC≥15000且CRP≥50）"
                                }
                              }
                            ],
                            "on_false": [
                              {
                                "type": "set",
                                "params": {
                                  "attr": "__exec__.payload.data.result.decision",
                                  "operation": "set",
                                  "value": "routine"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "medical_mfa_gate"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.operation.type",
                      "value": "read_medical_record"
                    },
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.auth.mfa_verified",
                      "value": false
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.1.d：病历读取需双因子认证，已阻断并留痕"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      }
    ]
  },
  "djbh": {
    "name": "MLPS 2.0 · access control",
    "desc": "Least-privilege: non-admins must not request admin (L3 §8.1.4.2.d)",
    "ruleCount": 4,
    "transform": [
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "djbh_mfa_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.operation_risk",
                      "value": "high"
                    },
                    {
                      "type": "lt",
                      "path": "__exec__.payload.data.mfa_factor_count",
                      "value": 2
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.1.d：高风险操作需双因子认证"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "djbh_access_control_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.requested_permission",
                      "value": "admin"
                    },
                    {
                      "type": "not",
                      "inner": {
                        "type": "eq",
                        "path": "__exec__.payload.data.user_role",
                        "value": "admin"
                      }
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.2.d：最小权限原则，非管理员不得请求管理员权限"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "djbh_audit_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "eq",
                  "path": "__exec__.payload.data.audit_enabled",
                  "value": false
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.3.a：安全审计未启用"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "branch",
                    "params": {
                      "domain": {
                        "type": "eq",
                        "path": "__exec__.payload.data.audit_log_protected",
                        "value": false
                      },
                      "on_true": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "warning"
                          }
                        },
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.reason",
                            "operation": "set",
                            "value": "等保2.0三级 §8.1.4.3.c：审计记录未受保护"
                          }
                        }
                      ],
                      "on_false": [
                        {
                          "type": "set",
                          "params": {
                            "attr": "__exec__.payload.data.result.decision",
                            "operation": "set",
                            "value": "compliant"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "djbh_confidentiality_check"
          },
          "on_true": [
            {
              "type": "set",
              "params": {
                "attr": "data",
                "operation": "set",
                "value": "__exec__.instruction.params"
              }
            },
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "all",
                  "inner": [
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.data_classification",
                      "value": "sensitive"
                    },
                    {
                      "type": "eq",
                      "path": "__exec__.payload.data.encryption",
                      "value": "none"
                    }
                  ]
                },
                "on_true": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "blocked"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.reason",
                      "operation": "set",
                      "value": "等保2.0三级 §8.1.4.8.b：敏感数据存储需加密"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "allowed"
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      }
    ]
  },
  "io": {
    "name": "External IO · effect layer",
    "desc": "io_request → external resolve → deterministic replay (D11 contract)",
    "ruleCount": 2,
    "transform": [
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "notify_request"
          },
          "on_true": [
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "not",
                  "inner": {
                    "type": "exists",
                    "path": "__exec__.payload.__io_result__"
                  }
                },
                "on_true": [
                  {
                    "type": "io_request",
                    "params": {
                      "io_type": "call_service",
                      "service_name": "__exec__.instruction.params.service_name",
                      "args?": "__exec__.instruction.params.args"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data",
                      "operation": "set",
                      "value": "__exec__.instruction.params"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "notified"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.io_status",
                      "operation": "set",
                      "value": "__exec__.payload.__io_result__.status"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.__io_result__",
                      "operation": "set",
                      "value": null
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      },
      {
        "type": "branch",
        "params": {
          "domain": {
            "type": "instruction",
            "instruction_type": "external_tool_request"
          },
          "on_true": [
            {
              "type": "branch",
              "params": {
                "domain": {
                  "type": "not",
                  "inner": {
                    "type": "exists",
                    "path": "__exec__.payload.__io_result__"
                  }
                },
                "on_true": [
                  {
                    "type": "io_request",
                    "params": {
                      "io_type": "call_external",
                      "tool_name": "__exec__.instruction.params.tool_name",
                      "arguments?": "__exec__.instruction.params.arguments"
                    }
                  }
                ],
                "on_false": [
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data",
                      "operation": "set",
                      "value": "__exec__.instruction.params"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.decision",
                      "operation": "set",
                      "value": "executed"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.data.result.io_status",
                      "operation": "set",
                      "value": "__exec__.payload.__io_result__.status"
                    }
                  },
                  {
                    "type": "set",
                    "params": {
                      "attr": "__exec__.payload.__io_result__",
                      "operation": "set",
                      "value": null
                    }
                  }
                ]
              }
            }
          ],
          "on_false": []
        }
      }
    ]
  }
};
export const SAMPLES = {
  "finance": {
    "type": "finance_expense_limit_check",
    "params": {
      "expense": {
        "type": "travel",
        "amount": 5000
      }
    }
  },
  "medical": {
    "type": "medical_antibiotic_tier_check",
    "params": {
      "prescription": {
        "antibiotic_tier": "special"
      },
      "visit": {
        "type": "outpatient"
      }
    }
  },
  "djbh": {
    "type": "djbh_access_control_check",
    "params": {
      "requested_permission": "admin",
      "user_role": "auditor"
    }
  },
  "io": {
    "type": "notify_request",
    "params": {
      "service_name": "approval-svc",
      "args": {
        "message": "expense 5000 needs approval"
      }
    }
  }
};
